version: '3.9'

services:
  redis_db:
    extends:
      file: ./services/docker-compose-redis.yml
      service: redis_db

  db-init:
    extends:
      file: ./services/docker-compose-db.yml
      service: db-init

  db:
    extends:
      file: ./services/docker-compose-db.yml
      service: db

  backend:
    depends_on:
      - db
      - redis_db
    extends:
      file: ./services/docker-compose-backend.yml
      service: backend
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        CACHE_EXCHANGE_RATES_PERIOD: ""
        API_V1_READ_METHODS_DISABLED: "false"
        DISABLE_WEBAPP: "false"
        API_V1_WRITE_METHODS_DISABLED: "false"
        CACHE_TOTAL_GAS_USAGE_COUNTER_ENABLED: ""
        CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL: ""
        ADMIN_PANEL_ENABLED: ""
        RELEASE_VERSION: 5.3.1
    links:
      - db:database
    environment:
        CHAIN_ID: '79'
        PORT: "4000"
        MIX_ENV: "prod"
        ACCOUNT_ENABLED: "false"
        SHOW_TESTNET_LABEL: "false"
        API_V2_ENABLED: "true"
        ECTO_USE_SSL: 'false'
        INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: 'true'
        INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
        DATABASE_URL: "postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@host.docker.internal:7432/blockscout?ssl=false"
        ETHEREUM_JSONRPC_VARIANT: "geth"
        ETHEREUM_JSONRPC_HTTP_URL: "https://dataserver-us-1.zenithchain.co"
        ETHEREUM_JSONRPC_TRACE_URL: "https://dataserver-us-1.zenithchain.co"
        SECRET_KEY_BASE: "56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN"
        ETHEREUM_JSONRPC_HTTP_TIMEOUT: "120"

  visualizer:
    extends:
      file: ./services/docker-compose-visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/docker-compose-sig-provider.yml
      service: sig-provider

  frontend:
    depends_on:
      - backend
    extends:
      file: ./services/docker-compose-frontend.yml
      service: frontend
    environment:
      NEXT_PUBLIC_NETWORK_SHORT_NAME: "Zenith"
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME: "Zenith"
      NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: "18"
      NEXT_PUBLIC_IS_ACCOUNT_SUPPORTED: "false"
      NEXT_PUBLIC_IS_TESTNET: "false"
      NEXT_PUBLIC_APP_HOST: "52.188.226.171:4000"
      NEXT_PUBLIC_API_HOST: "52.188.226.171"
      NEXT_PUBLIC_NETWORK_NAME: "Zenith"
      NEXT_PUBLIC_NETWORK_ID: "79"
      NEXT_PUBLIC_NETWORK_RPC_URL: "https://dataserver-us-1.zenithchain.co"
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: "Zenith"
      NEXT_PUBLIC_STATS_API_HOST: "localhost:8080"
      NEXT_PUBLIC_NETWORK_LOGO: ""
      NEXT_PUBLIC_API_PROTOCOL: http
      NEXT_PUBLIC_VISUALIZE_API_HOST: http://localhost:8081
      NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: ws
      NEXT_PUBLIC_API_BASE_PATH: /
      NEXT_PUBLIC_API_SPEC_URL: https://raw.githubusercontent.com/blockscout/blockscout-api-v2-swagger/main/swagger.yaml
      NEXT_PUBLIC_HOMEPAGE_PLATE_BACKGROUND: radial-gradient(circle farthest-corner at top right, #19C3CF 0%, #0A4A4D 100%);
      NEXT_PUBLIC_HOMEPAGE_PLATE_TEXT_COLOR: rgb(255, 255, 255)
      NEXT_PUBLIC_HOMEPAGE_SHOW_GAS_TRACKER: true

  stats-db-init:
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats-db-init

  stats-db:
    depends_on:
      - backend
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats
    environment:
      STATS_CHARTS__TEMPLATE_VALUES__NATIVE_COIN_SYMBOL: "zenith"


  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    extends:
      file: ./services/docker-compose-nginx.yml
      service: proxy
